
# Adapted from Shadertoy:
# https://www.shadertoy.com/view/XtdfW2

[shader]
Description=Vibrating beetle-like RGB bokeh-glare.
Byline=Adapted from work by ribenno @Shadertoy
VertexSourceTypeName=VertexQuad
FragmentShaderFilename=jitterbugs.frag

[audiotextures]
eyecandyShadertoy

[fx-blacklist]
skinimax
sobel
neon_motion
reaction
