
# Adapted from Shadertoy:
# https://www.shadertoy.com/view/llB3W1

[shader]
Description=Pulsing realtime renders of the Julia Set fractal.
Byline=Heavily modified work from relampago2048 and MV10 @Shadertoy
VertexSourceTypeName=VertexQuad
FragmentShaderFilename=julia_set.frag

[audiotextures]
eyecandyShadertoy

[fx-blacklist]
boxed
color_puddle
pixel_mist
reaction
sparkle
voronoi
whorls
