
# Adapted from Shadertoy:
# https://www.shadertoy.com/view/3XySWh
# https://www.shadertoy.com/view/3XGSDz

[shader]
Description=It'll reach out and drag you down#'
Byline=Original by HeaxaPhoenix and nayk @Shadertoy 
VertexSourceTypeName=VertexQuad
FragmentShaderFilename=vertigo.frag

[fx-blacklist]
blaze
boxed
color_puddle
extrusion
ghostly
hall_of_mirrors
mandelbrot
meltdown
nautilus
palette_knife
pixel_mist
rainbow_borders
sinusoid_warp
sketchy
staircase
time_blur
time_diffusion
trails
voronoi
whorls
