
[fx]
Description=Debug Test: HTTP image caching

# HTTP texture/cubemap entries support an optional Placeholder
# setting used when the image is being downloaded (or fails to load)
# This can be a texture filename in the configured texture path list,
# or an asterisk to use a single black pixel. See the test visualizer
# http-resize for an example using an image texture.
Placeholder = *

[multipass]
# draw  inputs  fx-shader (.frag extension not necessary)
  1     0       solarize.frag

[textures]
# randomly choose a NASA false-color solar image (updated every 15-30 minutes)
solar : !https://sdowww.lmsal.com/sdomedia/SunInTime/mostrecent/l_211_193_171.jpg
solar : !https://sdowww.lmsal.com/sdomedia/SunInTime/mostrecent/l0171.jpg
solar : !https://sdowww.lmsal.com/sdomedia/SunInTime/mostrecent/l0304.jpg
solar : !https://soho.nascom.nasa.gov/data/realtime/eit_171/1024/latest.jpg
