[shader]
Description=Debug Test: HTTP large-image resize and caching

VertexSourceTypeName=VertexQuad
FragmentShaderFilename=http-resize.frag

# HTTP texture/cubemap entries support an optional Placeholder
# setting used when the image is being downloaded (or fails to load)
# This can be a texture filename in the configured texture path list,
# or an asterisk to use a single black pixel. See the solarize test
# FX for an example using an asterisk.
Placeholder = Shadertoy London 512x512.jpg

[textures]
# Observatory construction panoramic
# https://www.eso.org/public/outreach/webcams/
# Original is 10000x3744 and are about 40MB
imageA : https://www.eso.org/public/archive_webcams/armazonespanosouth/public/poi/preset_100.jpg
