[shader]
Description=Debug Test: HTTP image caching

VertexSourceTypeName=VertexQuad
FragmentShaderFilename=http.frag

[textures]
# Jakarta traffic:          https://www.opentopia.com/webcam/18479
#imageA : https://images.opentopia.com/cams/18479/big.jpg

# forced download variant
# South Korean street:      https://www.opentopia.com/webcam/18247
#imageA : !https://images.opentopia.com/cams/18247/big.jpg

# randomized, forced downloads
# Chicago skyline:          https://www.opentopia.com/webcam/17508
# Illinois Dog Day Care:    https://www.opentopia.com/webcam/19030
# Michigan Dog Day Care:    https://www.opentopia.com/webcam/18178
imageA : !https://images.opentopia.com/cams/18479/big.jpg
imageA : !https://images.opentopia.com/cams/18247/big.jpg
imageA : !https://images.opentopia.com/cams/17508/big.jpg
imageA : !https://images.opentopia.com/cams/19030/big.jpg
imageA : !https://images.opentopia.com/cams/18178/big.jpg
