[shader]
Description=Debug Test: HTTP large-image resize and caching

VertexSourceTypeName=VertexQuad
FragmentShaderFilename=http-resize.frag

[textures]
# Observatory construction panoramic
# https://www.eso.org/public/outreach/webcams/
# Original is 10000x3744 and are about 40MB
imageA : https://www.eso.org/public/archive_webcams/armazonespanosouth/public/poi/preset_100.jpg
